name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '20'
      - name: Run test
        run: make run_test
      - name: Build Report
        run: make build_report
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: Extract_branch
      - name: Extract coverage result
        id: coverage
        run: echo "##[set-output name=coverage;]$(echo report/METHOD)"
      - name: Generate coverage badge
        uses: emibcn/badge-action@v1
        id: badge
        with:
          label: 'Coverage'
          status: ${{ steps.coverage.outputs.coverage }}
          path: .github/badges/test-coverage.svg
          color: ${{
            steps.coverage.outputs.coverage > 90 && 'green'              ||
            steps.coverage.outputs.coverage > 80 && 'yellow,green'       ||
            steps.coverage.outputs.coverage > 70 && 'yellow'             ||
            steps.coverage.outputs.coverage > 60 && 'orange,yellow'      ||
            steps.coverage.outputs.coverage > 50 && 'orange'             ||
            steps.coverage.outputs.coverage > 40 && 'red,orange'         ||
            steps.coverage.outputs.coverage > 30 && 'red,red,orange'     ||
            steps.coverage.outputs.coverage > 20 && 'red,red,red,orange' ||
            'red' }}
      - name: Commit badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .github/badges/test-coverage.svg
          git commit -m "Add/Update badge"
          - name: Push badge commit
            uses: ad-m/github-push-action@master
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              branch: ${{ steps.extract_branch.outputs.branch }}